# Generated by Django 4.1 on 2022-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('contact_number', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
