# Generated by Django 4.1 on 2022-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='imageUrl',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
